### ISSUE TITLE
Error: Cannot find module 'nativescript-angular/element-registry'

### ISSUE THREAD

**Issue by ketuvin** [saulshanabrook/nativescript-angular-webview-crypto#5]
I successfully installed the plugin in nativescript. And followed the steps to globally use the plugin. But when I build the app it returned an exception

Exception:
`An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: Cannot find module 'nativescript-angular/element-registry'
File: (file:///data/data/com.salusciens.medbook/files/app/runtime.js:31:12)

StackTrace: 
webpackMissingModule(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:95)
	at ./node_modules/nativescript-angular-webview-crypto/index.js(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:207)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
	at ./src/app/app.module.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:238:93)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
	at ./src/main.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:33:73)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at __webpack_exec__(file:///data/data/com.salusciens.medbook/files/app/bundle.js:993:39)
	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:111)
	at _webpack_require_.X(file:///data/data/com.salusciens.medbook/files/app/runtime.js:154:21)
	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:47)
	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:999:3)
	at require(:1:266)

Error: Cannot find module 'nativescript-angular/element-registry'

StackTrace:
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
Error: Cannot find module 'nativescript-angular/element-registry'
File: (file:///data/data/com.salusciens.medbook/files/app/runtime.js:31:12)

StackTrace: 
webpackMissingModule(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:95)
	at ./node_modules/nativescript-angular-webview-crypto/index.js(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:207)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
	at ./src/app/app.module.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:238:93)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
	at ./src/main.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:33:73)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at __webpack_exec__(file:///data/data/com.salusciens.medbook/files/app/bundle.js:993:39)
	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:111)
	at _webpack_require_.X(file:///data/data/com.salusciens.medbook/files/app/runtime.js:154:21)
	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:47)
	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:999:3)
	at require(:1:266)

Error: Cannot find module 'nativescript-angular/element-registry'
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5911)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.tns.NativeScriptException: Error calling module function 
Error: Cannot find module 'nativescript-angular/element-registry'
File: (file:///data/data/com.salusciens.medbook/files/app/runtime.js:31:12)

StackTrace: 
webpackMissingModule(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:95)
	at ./node_modules/nativescript-angular-webview-crypto/index.js(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:207)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
	at ./src/app/app.module.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:238:93)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
	at ./src/main.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:33:73)
	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
	at __`

Logcat:
`08-28 12:43:51.132 29529 29529 I usciens.medboo: Late-enabling -Xcheck:jni
08-28 12:43:52.241 29529 29529 I Perf    : Connecting to perf service.
08-28 12:43:52.430 29529 29554 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
08-28 12:43:52.439 29529 29529 I FirebaseInitProvider: FirebaseApp initialization successful
08-28 12:43:52.470 29529 29557 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
08-28 12:43:52.481 29529 29557 I FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
08-28 12:43:52.531 29529 29553 I FA      : App measurement initialized, version: 21028
08-28 12:43:52.531 29529 29553 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
08-28 12:43:52.531 29529 29553 I FA      : To enable faster debug mode event logging run:
08-28 12:43:52.531 29529 29553 I FA      :   adb shell setprop debug.firebase.analytics.app com.salusciens.medbook
08-28 12:43:52.630 29529 29529 I TNS.Runtime: NativeScript Runtime Version 7.0.1, commit no commit sha was provided by build.gradle build
08-28 12:43:52.745 29529 29552 D SharedPreferencesImpl: Time required to fsync /data/user/0/com.salusciens.medbook/shared_prefs/com.google.android.gms.measurement.prefs.xml: [<1: 0, <2: 0, <4: 0, <8: 0, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 1, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
08-28 12:43:52.807 29529 29529 D TNS.Runtime: V8 version 8.3.110.9
08-28 12:43:55.396 29529 29529 I org.libsodium.jni.NaCl: librarypath=/system/lib64:/system/vendor/lib64
08-28 12:43:55.606 29529 29529 D AndroidRuntime: Shutting down VM
08-28 12:43:55.608 29529 29529 E AndroidRuntime: FATAL EXCEPTION: main
08-28 12:43:55.608 29529 29529 E AndroidRuntime: Process: com.salusciens.medbook, PID: 29529
08-28 12:43:55.608 29529 29529 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.608 29529 29529 E AndroidRuntime: File: (file:///data/data/com.salusciens.medbook/files/app/runtime.js:31:12)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: StackTrace: 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: webpackMissingModule(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:95)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at ./node_modules/nativescript-angular-webview-crypto/index.js(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:207)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at ./src/app/app.module.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:238:93)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at ./src/main.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:33:73)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_exec__(file:///data/data/com.salusciens.medbook/files/app/bundle.js:993:39)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:111)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_require__.X(file:///data/data/com.salusciens.medbook/files/app/runtime.js:154:21)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:47)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:999:3)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at require(:1:266)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5911)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6762)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: Caused by: com.tns.NativeScriptException: Error calling module function 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.608 29529 29529 E AndroidRuntime: File: (file:///data/data/com.salusciens.medbook/files/app/runtime.js:31:12)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: StackTrace: 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: webpackMissingModule(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:95)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at ./node_modules/nativescript-angular-webview-crypto/index.js(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:207)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at ./src/app/app.module.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:238:93)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at ./src/main.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:33:73)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_exec__(file:///data/data/com.salusciens.medbook/files/app/bundle.js:993:39)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:111)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at __webpack_require__.X(file:///data/data/com.salusciens.medbook/files/app/runtime.js:154:21)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:47)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:999:3)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at require(:1:266)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 
08-28 12:43:55.608 29529 29529 E AndroidRuntime: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at com.tns.Runtime.runModule(Native Method)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at com.tns.Runtime.runModule(Runtime.java:689)
08-28 12:43:55.608 29529 29529 E AndroidRuntime: 	at com.tns.Runtime.run(Runtime.java:681)
08-28 12:43:55.609 29529 29529 E AndroidRuntime: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
08-28 12:43:55.609 29529 29529 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
08-28 12:43:55.609 29529 29529 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5906)
08-28 12:43:55.609 29529 29529 E AndroidRuntime: 	... 8 more
08-28 12:43:55.618 29529 29529 W System.err: An uncaught Exception occurred on "main" thread.
08-28 12:43:55.618 29529 29529 W System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
08-28 12:43:55.618 29529 29529 W System.err: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.618 29529 29529 W System.err: File: (file:///data/data/com.salusciens.medbook/files/app/runtime.js:31:12)
08-28 12:43:55.618 29529 29529 W System.err: 
08-28 12:43:55.618 29529 29529 W System.err: StackTrace: 
08-28 12:43:55.618 29529 29529 W System.err: webpackMissingModule(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:95)
08-28 12:43:55.618 29529 29529 W System.err: 	at ./node_modules/nativescript-angular-webview-crypto/index.js(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:207)
08-28 12:43:55.618 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.618 29529 29529 W System.err: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.618 29529 29529 W System.err: 	at ./src/app/app.module.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:238:93)
08-28 12:43:55.618 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.618 29529 29529 W System.err: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.618 29529 29529 W System.err: 	at ./src/main.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:33:73)
08-28 12:43:55.618 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.618 29529 29529 W System.err: 	at __webpack_exec__(file:///data/data/com.salusciens.medbook/files/app/bundle.js:993:39)
08-28 12:43:55.618 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:111)
08-28 12:43:55.618 29529 29529 W System.err: 	at __webpack_require__.X(file:///data/data/com.salusciens.medbook/files/app/runtime.js:154:21)
08-28 12:43:55.618 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:47)
08-28 12:43:55.618 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:999:3)
08-28 12:43:55.618 29529 29529 W System.err: 	at require(:1:266)
08-28 12:43:55.618 29529 29529 W System.err: 
08-28 12:43:55.618 29529 29529 W System.err: 
08-28 12:43:55.618 29529 29529 W System.err: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.618 29529 29529 W System.err: 
08-28 12:43:55.618 29529 29529 W System.err: StackTrace:
08-28 12:43:55.618 29529 29529 W System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
08-28 12:43:55.618 29529 29529 W System.err: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.618 29529 29529 W System.err: File: (file:///data/data/com.salusciens.medbook/files/app/runtime.js:31:12)
08-28 12:43:55.619 29529 29529 W System.err: 
08-28 12:43:55.619 29529 29529 W System.err: StackTrace: 
08-28 12:43:55.619 29529 29529 W System.err: webpackMissingModule(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:95)
08-28 12:43:55.619 29529 29529 W System.err: 	at ./node_modules/nativescript-angular-webview-crypto/index.js(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:207)
08-28 12:43:55.619 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.619 29529 29529 W System.err: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.619 29529 29529 W System.err: 	at ./src/app/app.module.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:238:93)
08-28 12:43:55.619 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.619 29529 29529 W System.err: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.619 29529 29529 W System.err: 	at ./src/main.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:33:73)
08-28 12:43:55.619 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.619 29529 29529 W System.err: 	at __webpack_exec__(file:///data/data/com.salusciens.medbook/files/app/bundle.js:993:39)
08-28 12:43:55.619 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:111)
08-28 12:43:55.619 29529 29529 W System.err: 	at __webpack_require__.X(file:///data/data/com.salusciens.medbook/files/app/runtime.js:154:21)
08-28 12:43:55.619 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:47)
08-28 12:43:55.619 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:999:3)
08-28 12:43:55.619 29529 29529 W System.err: 	at require(:1:266)
08-28 12:43:55.619 29529 29529 W System.err: 
08-28 12:43:55.619 29529 29529 W System.err: 
08-28 12:43:55.619 29529 29529 W System.err: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.619 29529 29529 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5911)
08-28 12:43:55.619 29529 29529 W System.err: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
08-28 12:43:55.619 29529 29529 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
08-28 12:43:55.619 29529 29529 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-28 12:43:55.619 29529 29529 W System.err: 	at android.os.Looper.loop(Looper.java:193)
08-28 12:43:55.619 29529 29529 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6762)
08-28 12:43:55.619 29529 29529 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 12:43:55.619 29529 29529 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-28 12:43:55.619 29529 29529 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-28 12:43:55.619 29529 29529 W System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
08-28 12:43:55.619 29529 29529 W System.err: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.619 29529 29529 W System.err: File: (file:///data/data/com.salusciens.medbook/files/app/runtime.js:31:12)
08-28 12:43:55.619 29529 29529 W System.err: 
08-28 12:43:55.619 29529 29529 W System.err: StackTrace: 
08-28 12:43:55.619 29529 29529 W System.err: webpackMissingModule(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:95)
08-28 12:43:55.620 29529 29529 W System.err: 	at ./node_modules/nativescript-angular-webview-crypto/index.js(file:///data/data/com.salusciens.medbook/files/app/vendor.js:140410:207)
08-28 12:43:55.620 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.620 29529 29529 W System.err: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.620 29529 29529 W System.err: 	at ./src/app/app.module.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:238:93)
08-28 12:43:55.620 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.620 29529 29529 W System.err: 	at fn(file:///data/data/com.salusciens.medbook/files/app/runtime.js:221:21)
08-28 12:43:55.620 29529 29529 W System.err: 	at ./src/main.ts(file:///data/data/com.salusciens.medbook/files/app/bundle.js:33:73)
08-28 12:43:55.620 29529 29529 W System.err: 	at __webpack_require__(file:///data/data/com.salusciens.medbook/files/app/runtime.js:28:33)
08-28 12:43:55.620 29529 29529 W System.err: 	at __webpack_exec__(file:///data/data/com.salusciens.medbook/files/app/bundle.js:993:39)
08-28 12:43:55.620 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:111)
08-28 12:43:55.620 29529 29529 W System.err: 	at __webpack_require__.X(file:///data/data/com.salusciens.medbook/files/app/runtime.js:154:21)
08-28 12:43:55.620 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:994:47)
08-28 12:43:55.620 29529 29529 W System.err: 	at (file:///data/data/com.salusciens.medbook/files/app/bundle.js:999:3)
08-28 12:43:55.620 29529 29529 W System.err: 	at require(:1:266)
08-28 12:43:55.620 29529 29529 W System.err: 
08-28 12:43:55.620 29529 29529 W System.err: 
08-28 12:43:55.620 29529 29529 W System.err: Error: Cannot find module 'nativescript-angular/element-registry'
08-28 12:43:55.620 29529 29529 W System.err: 	at com.tns.Runtime.runModule(Native Method)
08-28 12:43:55.620 29529 29529 W System.err: 	at com.tns.Runtime.runModule(Runtime.java:689)
08-28 12:43:55.620 29529 29529 W System.err: 	at com.tns.Runtime.run(Runtime.java:681)
08-28 12:43:55.620 29529 29529 W System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
08-28 12:43:55.620 29529 29529 W System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
08-28 12:43:55.620 29529 29529 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5906)
08-28 12:43:55.620 29529 29529 W System.err: 	... 8 more
08-28 12:43:55.636 29529 29529 I Process : Sending signal. PID: 29529 SIG: 9
`

I'm using the latest version of Nativescript (Version 8.0.7)

**Comment by ketuvin** [comment]
I fixed this issue. I found the cause of this error when I looked into the files in node_modules/nativescript-angular-webview-crypto
- index.ts
- index.js

In index.ts, I changed the `import {registerElement} from "nativescript-angular/element-registry";` to the correct path `import {registerElement} from "@nativescript/angular";` and applied the same thing in index.js.
![image](https://user-images.githubusercontent.com/33052653/131209580-193c49cd-02ef-4422-bfb5-386100f20646.png)
This fix the issue but then I noticed that there was another exception this time the nativescript-webview-crypto is not found. I already checked and it was pointing to the right path and the module is present and not missing.

PS. Directly editing the code of the package is a bad idea. This should be submitted as a pull request.
